### ISSUE TITLE
Which steam id we need for login?

### ISSUE THREAD

**Issue by CankatSoysal** [sometastycake/bufflogin#2]
and Will the login stay as login?

**Comment by sometastycake** [comment]
You need steamid like https://steamcommunity.com/profiles/**76561198432348171**/

> and Will the login stay as login?
If you use default cookie storage, then no. To stay authorized in buff.163.com (even after application restarting) you need store session cookies. Session cookies stores in application memory by default
You can define own cookie storage, for example, redis storage: https://github.com/sometastycake/pysteamauth
